### ISSUE TITLE
Publish app on F-Droid

### ISSUE THREAD

**Issue by IzzySoft** [MarquisLP/WorldScribe#12]
With your app being open source, would you mind having it available on F-Droid? From what I can see, it would fit their inclusion criteria.

Hoping for your agreement, I've already [opened a request for packaging](https://gitlab.com/fdroid/rfp/issues/648).

**Comment by MarquisLP** [comment]
Hi @IzzySoft , I would be more than happy to have the app on F-Droid!

From what I understand, the F-Droid team will handle the inclusion process, but is there anything more that needs to be done on my end?

**Comment by IzzySoft** [comment]
Glad to read, @MarquisLP – that's great! Yes, maybe you could add the [distributionSha256Sum](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:verification) to your gradle, as [the F-Droid Bot suggests](https://gitlab.com/fdroid/rfp/issues/648#note_88120869)?

I wonder that the F-Droid Bot didn't complain about Dropbox; is that library FOSS? In case a maintainer considers it a "show-stopper": would a flavor without Dropbox be a possibility? As I understand it, that's just for backup purposes and not essential to the app itself (after all, one could use a different app for backup purposes)?

**Comment by IzzySoft** [comment]
OK, just got to know Dropbox SDK uses MIT license and thus is "whitelisted". The RFP is currently looked at by a dev. Could you please meanwhile fix this minor nuisance in the gradle? Then we should be ready to go.

**Comment by MarquisLP** [comment]
Good to hear! I'll see if I can add the SHA checksum later today.

**Comment by MarquisLP** [comment]
Alright, the SHA-256 checksum is now [up and running](https://github.com/MarquisLP/World-Scribe/blob/master/gradle/wrapper/gradle-wrapper.properties)!

**Comment by IzzySoft** [comment]
Great! Then a dev will take over from me to process it. Thanks a lot!

**Comment by IzzySoft** [comment]
Yay, cool!

**Comment by MarquisLP** [comment]
Hi @IzzySoft , quick question about the F-Droid integration: do updates in this repository automatically get published to F-Droid? Or is there some manual work that needs to be done before an update gets posted?

**Comment by Poussinou** [comment]
@MarquisLP 

As you can see in this [file](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.averi.worldscribe.txt), new versions will be taken automatically, as long as you tag them accurately :)

1.4.7 should appear in a few hours/days on F-Droid

**Comment by IzzySoft** [comment]
The lines @Poussinou refers to:

    Auto Update Mode:Version %v
    Update Check Mode:Tags

"Check for (new) tags whose name is higher than the current version" :wink:

**Comment by MarquisLP** [comment]
I see, thanks again guys! :smiley:
