### ISSUE TITLE
Add options to change GUI scale and text size in application

### ISSUE THREAD

**Issue by kadoha** [MarquisLP/WorldScribe#17]
It will be very convenient if such options exist, because on relatively small screen devices some buttons and text appears too large. Even if I set Font and Display size to smallest values possible in global Android setings at Accessibility section, some World Scribe GUI elements still quite big.

Thanks!

**Comment by MarquisLP** [comment]
Thanks for the suggestion! This has been implemented in [version 1.5.0](https://github.com/MarquisLP/World-Scribe/releases/tag/1.5.0).
