### ISSUE TITLE
Display a Privacy Policy in the app

### ISSUE THREAD

**Issue by MarquisLP** [MarquisLP/WorldScribe#34]
Because Flipper uses `androidx.preferences`, the Google Play Store requires that the app display a Privacy Policy before version 1.6.0 can be published there.

Since World Scribe does _not_ collect or transmit user data in any way, the privacy policy should explain that all user content is kept private to their device (as well as their private Dropbox and/or NextCloud accounts if they are integrated). Even beyond the Google Play requirement, this would be a good thing to add in order to be transparent to new users.

We can display this policy in a new Activity that appears before the Permissions Activity.

**Comment by MarquisLP** [comment]
The new Activity, named `PrivacyPolicyActivity`, has been implemented as described above, as well as merged into `develop`.

@tostc can I ask for your help once more in translating the new strings into German? In `values-de/string.xml`, the strings are called:
-  `privacyPolicyTitle`
-  `privacyPolicyContent`
-  `privacyPolicyAgreeButton`
-  `privacyPolicyDisagreeButton`

**Comment by tostc** [comment]
Translation is added.
