### ISSUE TITLE
[Feature Request] Translation in Google Play and fdroid

### ISSUE THREAD

**Issue by tostc** [MarquisLP/WorldScribe#37]
Hi,

I was questining me, if you can add translations in Google Play and fdroid? If it so, should I translate these?

**Comment by MarquisLP** [comment]
Hi! Translating the Google Play and F-Droid information would be a great idea. The changelog would also be a good thing to translate (right now, it's pretty jarring having it in English while the rest of the app is in German, haha).

I'm a bit short on time right now, but I'll look into this over the week, and try to get back to you this weekend on how we should organize this.

**Comment by MarquisLP** [comment]
I've created a Google Doc for store listing translations [here](https://docs.google.com/document/d/1KhXMfPvFaVtDJ3_i_tvpK7wnA-QtYTOGhi3jDhywmlE/edit?usp=sharing). Just request edit access using your Gmail account, then once I approve you can fill in the 'German' section.

Anyone looking to provide translations for other languages are welcome to request access as well.

(Also, I've moved the changelog translation to a separate issue at #38.)

**Comment by tostc** [comment]
I've added the translation to the document.

**Comment by MarquisLP** [comment]
After an unplanned delay, I've finally published the German version of the Play Store page.

@tostc Can I ask for your help in translating the tagline that appears in the promo graphic as well? I've added it at the bottom of the Google Doc.

**Comment by tostc** [comment]
I've translated the promo tag.

**Comment by MarquisLP** [comment]
Thanks for the quick work :smiley: The new promo image has been uploaded. And with that, the translation is complete.
