### ISSUE TITLE
Privacy policy Layout fix

### ISSUE THREAD

**Issue by tostc** [MarquisLP/WorldScribe#40]
Hi,

can you make the "Accept" and "Denied" Button in the privacy police layout the same size?

![Screenshot_20200120-191929_World Scribe](https://user-images.githubusercontent.com/46672880/72749498-83d5bc80-3bba-11ea-9d6d-058c365cbd6f.jpg)
This is a screenshot of my Phone. Samsung Galaxy A8 Android 9

**Comment by MarquisLP** [comment]
Hi, thanks for bringing this up. This seems to be a problem with the layout weights on the buttons. I'll look into this soon.

**Comment by tostc** [comment]
Both buttons width are equal. Thanks for fixing :smile:
