### ISSUE TITLE
German translation for 1.6.1 release

### ISSUE THREAD

**Issue by MarquisLP** [MarquisLP/WorldScribe#46]
Hi @tostc , can I ask for your help in translating the following items for version 1.6.1?

- [New changelog entry for 1.6.1](https://github.com/MarquisLP/World-Scribe/blob/0b373c21c8e298d7327e956f011989e1650cf450/app/src/main/res/raw/changelog.xml#L5)
- [The 'Developer Website' menu option text](https://github.com/MarquisLP/World-Scribe/blob/0b373c21c8e298d7327e956f011989e1650cf450/app/src/main/res/values/strings.xml#L38)

**Comment by MarquisLP** [comment]
Hi again @tostc , I was able to find a solution to #43 and verify it with a user, so I'm planning to add one more item to the changelog. As such, could you please translate the following as well? (You can post the translation here as a comment, rather than in a pull request, as I haven't added this to the changelog file yet.)

"**Crashes during storage location selection have been fixed!** However, if you're still encountering crashes or other issues, please don't hesitate to reach out to us at averistudios@gmail.com."

**Comment by tostc** [comment]
" **Abstürze bei der Auswahl des Speicherortes wurden behoben!** Wenn Sie jedoch weiterhin auf Abstürze oder andere Probleme stoßen, wenden Sie sich bitte an averistudios@gmail.com."

**Comment by MarquisLP** [comment]
Thank you :smile:
