### ISSUE TITLE
German Translation for 1.6.2

### ISSUE THREAD

**Issue by MarquisLP** [MarquisLP/WorldScribe#52]
Hi @tostc , can I please ask for your help in translating the following changelog text for version 1.6.2?

> [b]We've resolved the issue preventing certain Android 10 devices from getting past the 'Data Location' setup screen.[/b] Thank you to all affected users for being patient, and an especially big thank you to all the users who helped out with testing!

(The updated changelog hasn't been pushed yet, so you can just post the translation as a reply here.)

**Comment by tostc** [comment]
Hi @MarquisLP,

no problem here the translated text.

> [b]Wir haben das Problem gelöst, das bestimmte Android 10-Geräte daran hindert, über den Einstellungsbildschirm 'Datenspeicherort' hinauszukommen.[/b] Vielen Dank an alle betroffenen Benutzer für ihre Geduld, und ein besonders großes Dankeschön an alle Benutzer, die bei den Tests mitgeholfen haben!

**Comment by MarquisLP** [comment]
Thanks once again! :smiley:
